server:
  port: 8080

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: Root123456
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
